FROM python:3.12

WORKDIR /app

RUN apt-get update && apt-get install -y netcat-openbsd


COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

COPY . .

RUN chmod +x entrypoint.sh

ENTRYPOINT ["./entrypoint.sh"]